### ISSUE TITLE
No user in Users/manage: "No data available in table"

### ISSUE THREAD

**Issue by SkeeeRoy** [Piwigo/Piwigo#882]
Hi,

I've finally done the jump from Piwigo version 2.7.4 to version 2.9.3 with a manual upgrade.
My few users can seen in the album permission settings, in the groups settings, but the user list is empty in the Users/manage with the indication "No data available in table".
If I remember well, even guest and admin users are supposed to be shown there.

The login of the users doesn't seem nevertheless to be a problem.
Interestingly it shows in the same time:

> Showing 0 to 0 of 0 entries
but as well:
> No User Selected out of 13

Piwigo 2.9.3
Système d'exploitation: Linux
PHP: 5.6.8 (Montrer les informations) [2018-06-15 09:55:12]
MySQL: 5.0.83 [2018-06-15 09:55:12]
Bibliothèque graphique: GD bundled (2.1.0 compatible)
Hosted by free.fr with the "preg_split" code modification.

**Comment by lolomin** [comment]
Hi,

I have the same problem, Users informations does not display when I go to Users / Manage.
But users are here because If I click on All, I can see it displays "<xx> users are selected".

Regards,

lolomin

**Comment by lolomin** [comment]
Hi,

@SkeeeRoy, did you succeed to fix this problem please ?

Regards,

lolomin

**Comment by SkeeeRoy** [comment]
Sorry it's not installed so far, as there's an error in the autoupdate. I guess it comes from the hosting "Free".
As I have to do it manually, it's not done so far :(

**Comment by lolomin** [comment]
No it's not, problem still exists with latest version...

**Comment by flop25** [comment]
Free is well known to have many limitations
Check out our french forum

about the users not displayed, again search in our forums: it cna comes from an hidden server errror message, missing json module in php...

**Comment by lolomin** [comment]
Hi flop25,

thanks for your answer but personnaly I host my own piwigo instance on my own dedicated linux server at home so I have total control over the server and am unable to find any errors about the problem of users which are not displaying under Users/Manage (I'm in French so sorry if translation is not 100% the good one).
Do you have any clue on what to do ? any debug mode or other thing to do to find the cause of this problem please ?

Regards,

lolomin

**Comment by PasiJarnstedt** [comment]
I'm having also this issue with update to 2.9.4. 

It seems that user list is populated by jquery by calling <URLTOPIWIGO>/ws.php?format=json&method=pwg.users.getList


For me this returns valid list of all users in Piwigo, but somehow the JS does not create the list. 

The code seems to be added in admin.php?page=user_list as <script type="text/JavaScript">//<![CDATA ………. </script>

Could not figure out anything more in last hour.

**Comment by doophy** [comment]
I am also seeing this problem. Running 2.9.4. When I look at piwigo_users, I see my user info. In the web admin manage users page, I see "No data available in table", but when I slect all, it shows All 7 users are selected, which matches the number of entries in the users table. Looking at groups, I see the usernames in the groups I've set up.

**Comment by lolomin** [comment]
It seems this problem affect many users but is totally ignore by development team since we do not have the once of an answer about considering to have a look at this problem ?

**Comment by in8sworld** [comment]
This is very frustrating since I'm not sure how to troubleshoot it.  The user table doesn't get populated.
**mjh75** mentioned it in this thread when upgrading to 2.9.1:
https://piwigo.org/forum/viewtopic.php?id=28224
I'm at 2.9.4 and not sure when it happened exactly since I don't have a lot of users and my login works fine.  There are no errors in the console of Firefox's inspector, nothing in the logs on my server regarding an error.  It must be javascript.  If I have the inspector open and I try to do anything like add a user or query the status on the users an error does appear in the console:
`TypeError: oTable.api is not a function`
Firefox says the error is in admin.php but its obviously elsewhere where it tries to draw the table:
`jQuery.ajax({
      url: "ws.php?format=json&method="+method,
      type:"POST",
      data: data,
      beforeSend: function() {
        jQuery("#applyActionLoading").show();
      },
      success:function(data) {
        oTable.api().draw();
        jQuery("#applyActionLoading").hide();
        jQuery("#applyActionBlock .infos").show();`

**Comment by in8sworld** [comment]
I just wanted to follow up on this. I download the latest version 2.9.4 and expanded it, renamed my gallery folder to move it out of the way and renamed the unzipped piwigo folder to replace it.  I copied the config files from the original install over, then copied over my theme (and sub-theme), my galleries folder, and the upload folder.  Loaded up the site and - everything is working perfectly.  I tried to diff some key folders to see what might be different but haven't found anything yet.  However, my user list is now populated properly.

**Comment by SkeeeRoy** [comment]
Hi all, yes you're right, 
as my host is the french "free", i need to proceed to manual upgrades each time, and i had not taken the time to do it since now.

With the manual upgrade to 2.9.4 the userlist appears again. The problem is solved I guess.
